<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1

Purely from memory, write short descriptions of the following terms:

1. Subsetting
- *To select elements from a list or array*

1. Indexing
- *To select one element from a list or array*

1. Slicing
- To choose a set of elements within a list or array from a specified range

1. Masking
- To choose a set of elements from a list or array that satisfy certain criteria

# Exercise 2

In [2]:
import numpy as np

In [3]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

Use masking to subset the letters that correspond to the odd numbers. i.e., get the result `[A, C, E, G, I]`.

In [4]:
numbers_array=np_array_2d[:, 0]
numbers_array

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U11')

In [20]:
numbers_array = numbers_array.astype(int)

In [21]:
numbers_array%2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int32)

In [26]:
new_numbers=numbers_array%2
new_numbers

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int32)

In [27]:
odd_numbers_mask = new_numbers > 0
odd_numbers_mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [28]:
np_array_2d[odd_numbers_mask, 1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')