<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [2]:
import numpy as np

# Lists, Arrays & Dictionaries

## Let’s compare

## Accessing data from a list (or array)

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

py_real_names[0]

'Natasha Romanoff'

In [3]:
py_super_names[-1]   # Reverse indexing

'Doctor Strange'

## Accessing data from a dictionary

In [6]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

In [7]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [8]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## Higher dimensional lists

In [9]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# Lists vs. Arrays

## Size

In [11]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [12]:
np_array_2d.shape

(10, 2)

## Arrays are fussy about type

In [10]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [13]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## Adding a number

In [14]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [15]:
np_array - 10

array([-9, -8, -7, -6, -5])

In [16]:
np_array + 20

array([21, 22, 23, 24, 25])

## Adding another list

In [17]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [19]:
py_list_3 = py_list_1 + py_list_2

In [20]:
py_list_3

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

## Multiplying by a Number

In [3]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [4]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [5]:
py_list*1.5

TypeError: can't multiply sequence by non-int of type 'float'

In [6]:
np_array*1.5

array([1.5, 3. , 4.5, 6. , 7.5])

## Squaring

In [7]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [8]:
np_array**0.5

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [9]:
py_list**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## Asking questions

In [10]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [11]:
py_list == 5

False

In [18]:
np_array == np_array

array([ True,  True,  True,  True,  True])

## Mathematics

In [19]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [20]:
np_array.std()

1.4142135623730951

In [22]:
np_array.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'