<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# Subsetting: Indexing and Slicing

In [1]:
import numpy as np

## Lists & Arrays in 1D | Subsetting & Indexing

In [2]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [3]:
x[0]

'a1'

In [4]:
x[::-1]

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

In [5]:
x

array(['a1', 'b2', 'c3', 'd4', 'e5', 'f6', 'g7', 'h8', 'i9', 'j10'],
      dtype='<U3')

## Arrays only | Subsetting by masking

In [6]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [7]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
np_array[np_array >= 3]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np_array[~(np_array == 3)]                 # '~' means 'NOT'

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10])

## Lists & Arrays in 2D | Indexing & Slicing

In [11]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [12]:
np_array_2d[-3]

array(['8', 'H'], dtype='<U11')

In [13]:
np_array_2d[-3, -1]

'H'

In [14]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

In [15]:
py_list_2d[:3][0]

[1, 'A']

In [16]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U11')

In [17]:
py_list_2d[3:6][0]

[4, 'D']

## Growing lists

In [18]:
x = [1, 2, 3]
x += [4, 5, 6]
x
x=[1, 2, 3]
x.extend([4, 5, 6])
x
x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## Tuples

In [21]:
a=(1, 2, 3)     # Define tuple
a[0]

1

In [30]:
a.append(10)
a

AttributeError: 'tuple' object has no attribute 'append'

In [28]:
b=[3, 4, 5]
b

[3, 4, 5]

In [29]:
b.append(10)
b

[3, 4, 5, 10]

## Be VERY careful when copying

In [31]:
x=[1, 2, 3]
w=[4, 5, 6]
y=x.copy()
y

[1, 2, 3]

In [32]:
z=x.copy() + w.copy()
z

[1, 2, 3, 4, 5, 6]